name: Deploy Android staging build with APK file

on:
  push:
    branches:
      - develop
      - 'release/**'

jobs:
  build_and_deploy_android:
    name: Build and deploy Android staging APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.3.0

    - name: Setup Java environment
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Set up Flutter version
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.8'

    - name: Setup .env.staging
      env:
        ENV_STAGING: ${{ secrets.ENV_STAGING }}
      run: echo $ENV_STAGING | base64 --decode >> .env.staging

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Run code generator script
      run: flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Build Android APK
      run: flutter build apk --flavor staging --debug --build-number $GITHUB_RUN_NUMBER

    - name: Upload Android Staging to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: Android-Staging-Build
        path: build/app/outputs/flutter-apk/app-staging-debug.apk
        